{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "headofcontext.fullname" . }}
  labels: {{- include "headofcontext.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "headofcontext.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from: {{- toYaml .Values.networkPolicy.ingressFrom | nindent 8 }}
      ports:
        - port: 8000
  egress:
    {{- range .Values.networkPolicy.egressCidrs }}
    - to:
        - ipBlock:
            cidr: {{ . | quote }}
    {{- end }}
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
{{- end }}
